#Python program request an integer value........
#The user must input a number  to show the integer value below.....


n = int(input("\n\nEnter an integer value: "))  #The user must type any number between 1 to 100.
if(n>=1 and n<=100):
    print("\nOK\n")               
else:
    print("\nOut of range!.\n\n")    #If the integer value is more than 100...
    
    
#End process...