#Python program request an integer value........
#The user must input a number  to show the integer value below.....


n = int(input("Enter an integer value: "))  #The user must type any number between 1 to 100.
if(n>=1 and n<=100):
    print("OK")               
else:
    print("Out of range")    #If the integer value is more than 100...
    
    
#End process...